// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeMCKOB-a7O89t0v7GrwiYUrGL9Jf2lYA',
    appId: '1:929725783421:web:f5c9f68a6bdfef0c1f8014',
    messagingSenderId: '929725783421',
    projectId: 'grocerytrip-de0c4',
    authDomain: 'grocerytrip-de0c4.firebaseapp.com',
    databaseURL: 'https://grocerytrip-de0c4-default-rtdb.firebaseio.com',
    storageBucket: 'grocerytrip-de0c4.appspot.com',
    measurementId: 'G-5B5K3D8DC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi-zNr9YnEhXNDJsIzX7GNgfOxVqLE1Mo',
    appId: '1:929725783421:android:7c13acd5b6cadb531f8014',
    messagingSenderId: '929725783421',
    projectId: 'grocerytrip-de0c4',
    databaseURL: 'https://grocerytrip-de0c4-default-rtdb.firebaseio.com',
    storageBucket: 'grocerytrip-de0c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPG6C1KQ4loXexAxWBHVWvo3jWcbR1GmI',
    appId: '1:929725783421:ios:33602eda32dd6af61f8014',
    messagingSenderId: '929725783421',
    projectId: 'grocerytrip-de0c4',
    databaseURL: 'https://grocerytrip-de0c4-default-rtdb.firebaseio.com',
    storageBucket: 'grocerytrip-de0c4.appspot.com',
    iosClientId: '929725783421-3kvmin118djtol4spni5en1k56tu6ig9.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryTrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPG6C1KQ4loXexAxWBHVWvo3jWcbR1GmI',
    appId: '1:929725783421:ios:33602eda32dd6af61f8014',
    messagingSenderId: '929725783421',
    projectId: 'grocerytrip-de0c4',
    databaseURL: 'https://grocerytrip-de0c4-default-rtdb.firebaseio.com',
    storageBucket: 'grocerytrip-de0c4.appspot.com',
    iosClientId: '929725783421-3kvmin118djtol4spni5en1k56tu6ig9.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryTrip',
  );
}
